
title: Edwin Vans
email: vans.edw@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal blog and projects site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.edwinvans.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  edwinv87

# Build settings
theme: jekyll-theme-cayman

